{ nixpkgs }:
{
  "AARCH64_bcm2711_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_hikey_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_imx8mm_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_imx8mq_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_imx93_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_maaxboard_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_odroidc2_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_odroidc4_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_rockpro64_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_tqma_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_tx1_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_ultra96v2_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "AARCH64_zynqmp_verified" = nixpkgs.pkgsCross.aarch64-embedded.stdenv.cc;
  "ARM_am335x_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_bcm2837_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_exynos4_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_exynos5410_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_exynos5422_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_hikey_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_HYP_exynos5_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_HYP_exynos5410_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_HYP_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_imx8mm_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_MCS_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_omap3_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_tk1_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_zynq7000_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "ARM_zynqmp_verified" = nixpkgs.pkgsCross.armhf-embedded.stdenv.cc;
  "RISCV64_MCS_verified" = nixpkgs.pkgsCross.riscv64-embedded.stdenv.cc;
  "RISCV64_verified" = nixpkgs.pkgsCross.riscv64-embedded.stdenv.cc;
  "X64_verified" = nixpkgs.pkgsCross.x86_64-embedded.stdenv.cc;
}
